language: java

matrix:
  include:
  - os: linux
    # Use container-based build
    sudo: false
    # Build using JDK 8 environment
    jdk: oraclejdk8
    addons:
      apt:
        packages:
          # Ensure the newest java8 is installed
          - oracle-java8-installer
          # launch4j 3.9 currently ships with a 32bit winres binary for Linux,
          # which requires 32bit libraries to be installed on a 64bit system
          # The following should work for both Ubuntu 14.04 and 16.04 
          - lib32z1
    # Download and extract Alice 3
    install:
      - wget http://www.alice.org/downloads/installers/Alice3_unix_3_3_0.sh && sh ./Alice3_unix_3_3_0.sh -q

  - os: osx
    # Use the XCode 8.2 OSX image
    osx_image: xcode8.2
    # Download and extract Alice 3
    install:
      - wget http://www.alice.org/downloads/installers/Alice3_macos_3_3_0.dmg
      - MOUNTDIR=$(hdiutil mount ./Alice3_macos_3_3_0.dmg | head -n 1 | cut -s -f 3)
      - hdiutil mount ./Alice3_macos_3_3_0.dmg
      - echo "DMG mount dir=${MOUNTDIR}"
      - ls -al "${MOUNTDIR}"
      - sudo "${MOUNTDIR}/Alice 3 Installer.app/Contents/MacOS/JavaApplicationStub -q"

# Ensure Gradle cache folders are cleaned up
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Don't perform builds on GitHub Pages branch
# (it's disabled by default, but doesn't hurt to be explicit)
branches:
  except:
    - gh-pages

# The script to execute for the build
script: ./gradlew izPackCreateInstaller launch4j

deploy:
  provider: releases
  api_key:
    secure: "GIKoC+6BFF0a2vmdrOGIqfObkh3nJ7c48Y5DiHOlTuqFzcamaFz2kVeFxbkXSsW1GD8dH1/gjJv/k+oxK3lT6zHeLoJJsQU7dAlF/csxyU0QRTyOnmfLk1Px9hJ/pU2iqPpv4UCNoiCcHt/MTUjHsWKFXLSGA1hdVDy0rLE2zFwDSq/sR69KpuXIkelqx8KSULT0Y13PSW+IBfNui/Jx8vhWjritdpkHFeZrPTtQZfn8e1Tg2eqppiBgXXIHM6D0jqWJv8hlIUJAE0lpwlQgZ1CoYpJ8Xf3z454pQIUFp+iiIuoeRXzQoFtqwAO2nJb3xbPaTuw/NgR2G8EKEblqDJh6RKXOgOaDBOAxM7bnKSSe4m895IsF3GUeMG22Ol9lLNXBvPRzX3nPrG9dkTDtmYHO4as8E/m4pbHkggeW9/zDBX9e8mnVtw148WGlMoG5XYzV8qgjWf67k4nedJp82WGiWOe/NebJHcnVe7UplQimBWNyX9yTpmFG8pGIj0UboypiToNMKFnqtkUeo94RpABq+bl9SmK7v2WMNkzKLwkLAqhSyuEum1mXy7+e+9Rt1Hwg9rV7k+152BEiV2t9oHzFAGcl86qFL5IEE7ej6IV6bfp0ygQtoUwJUgRYrZTxyEyzegdwxjYOuoI9rsQUdU7VMOHpNT03mPNlIyd79KI="
  file:
    - build/distributions/finch4alice-*-installer.jar
    - build/distributions/finch4alice-*-setup.exe
  file_glob: true
  skip_cleanup: true
  on:
    tags: true